// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUUP4eS6wJswHNIxSCKnES323xL8qRSk8',
    appId: '1:923921841429:web:4b59d4ba528941a1ad3d1c',
    messagingSenderId: '923921841429',
    projectId: 'medicate-c26dd',
    authDomain: 'medicate-c26dd.firebaseapp.com',
    storageBucket: 'medicate-c26dd.firebasestorage.app',
    measurementId: 'G-WF6X5FG8RL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCueQIs5ikQfwV3eWcAa4EVLQ3CC6ef6xA',
    appId: '1:923921841429:android:e19e43d6bfa1efc4ad3d1c',
    messagingSenderId: '923921841429',
    projectId: 'medicate-c26dd',
    storageBucket: 'medicate-c26dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy_wzISvZL8ZvZMw-_CAMXLUJOF_GWAOA',
    appId: '1:923921841429:ios:c06a6d6c0c7d37a3ad3d1c',
    messagingSenderId: '923921841429',
    projectId: 'medicate-c26dd',
    storageBucket: 'medicate-c26dd.firebasestorage.app',
    iosBundleId: 'com.medicate.medicate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy_wzISvZL8ZvZMw-_CAMXLUJOF_GWAOA',
    appId: '1:923921841429:ios:c06a6d6c0c7d37a3ad3d1c',
    messagingSenderId: '923921841429',
    projectId: 'medicate-c26dd',
    storageBucket: 'medicate-c26dd.firebasestorage.app',
    iosBundleId: 'com.medicate.medicate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUUP4eS6wJswHNIxSCKnES323xL8qRSk8',
    appId: '1:923921841429:web:d391b111e42a1e5ead3d1c',
    messagingSenderId: '923921841429',
    projectId: 'medicate-c26dd',
    authDomain: 'medicate-c26dd.firebaseapp.com',
    storageBucket: 'medicate-c26dd.firebasestorage.app',
    measurementId: 'G-1YXZPKBGHW',
  );
}
