import 'package:medicate_app/ui/dashboard/healthcare_provider_dashboard/specialists/specialists_providers_more_screen.dart';
import 'package:stacked/stacked.dart';
import 'package:stacked/stacked_annotations.dart';
import 'package:stacked_services/stacked_services.dart';
import '../../../ui/authentication/health_care/health_care_change_no_screen.dart';
import '../../../ui/authentication/health_care/health_care_doctor_specialist_signup_screen.dart';
import '../../../ui/authentication/health_care/health_care_forgot_pin_screen.dart';
import '../../../ui/authentication/health_care/health_care_hospital_and_clinic_signup_screen.dart';
import '../../../ui/authentication/health_care/health_care_login_screen.dart';
import '../../../ui/authentication/health_care/health_care_reset_pin_screen.dart';
import '../../../ui/authentication/health_care/health_care_reset_success_screen.dart';
import '../../../ui/authentication/health_care/health_care_setup_pin_screen.dart';
import '../../../ui/authentication/health_care/health_care_welcome_screen.dart';
import '../../../ui/authentication/hmo/hmo_change_no_screen.dart';
import '../../../ui/authentication/hmo/hmo_forgot_pin_screen.dart';
import '../../../ui/authentication/hmo/hmo_login_screen.dart';
import '../../../ui/authentication/hmo/hmo_reset_pin_screen.dart';
import '../../../ui/authentication/hmo/hmo_reset_success_screen.dart';
import '../../../ui/authentication/hmo/hmo_setup_pin_screen.dart';
import '../../../ui/authentication/hmo/hmo_signup_screen.dart';
import '../../../ui/authentication/hmo/hmo_welcome_screen.dart';
import '../../../ui/authentication/pharmacy/pharm_change_no_screen.dart';
import '../../../ui/authentication/pharmacy/pharm_forgot_pin_screen.dart';
import '../../../ui/authentication/pharmacy/pharm_login_screen.dart';
import '../../../ui/authentication/pharmacy/pharm_reset_pin_screen.dart';
import '../../../ui/authentication/pharmacy/pharm_reset_success_screen.dart';
import '../../../ui/authentication/pharmacy/pharm_setup_pin_screen.dart';
import '../../../ui/authentication/pharmacy/pharm_sign_up_screen.dart';
import '../../../ui/authentication/pharmacy/welcome_screen.dart';
import '../../../ui/authentication/user/change_phone_number.dart';
import '../../../ui/authentication/user/forgot_pin_screen.dart';
import '../../../ui/authentication/user/login_screen.dart';
import '../../../ui/authentication/user/reset_pin_screen.dart';
import '../../../ui/authentication/user/setup_pin_screen.dart';
import '../../../ui/authentication/user/sign_up_screen.dart';
import '../../../ui/authentication/user/success_screen.dart';
import '../../../ui/authentication/user/welcome_screen.dart';
import '../../../ui/dashboard/ask_me_screen.dart';
import '../../../ui/dashboard/dashboard_screen.dart';
import '../../../ui/dashboard/healthcare_provider_dashboard/business_owners/business_provider_add_to_cart_screen.dart';
import '../../../ui/dashboard/healthcare_provider_dashboard/business_owners/business_provider_dashboard.dart';
import '../../../ui/dashboard/healthcare_provider_dashboard/business_owners/business_provider_order_screen.dart';
import '../../../ui/dashboard/healthcare_provider_dashboard/business_owners/business_provider_whole_sale_checkout.dart';
import '../../../ui/dashboard/healthcare_provider_dashboard/business_owners/business_providers_home_screen.dart';
import '../../../ui/dashboard/healthcare_provider_dashboard/business_owners/business_providers_more_screen.dart';
import '../../../ui/dashboard/healthcare_provider_dashboard/reminder/healthcare_view_medication_screen.dart';
import '../../../ui/dashboard/healthcare_provider_dashboard/specialists/specialists_provider_add_to_cart_screen.dart';
import '../../../ui/dashboard/healthcare_provider_dashboard/specialists/specialists_provider_dashboard.dart';
import '../../../ui/dashboard/healthcare_provider_dashboard/specialists/specialists_provider_order_screen.dart';
import '../../../ui/dashboard/healthcare_provider_dashboard/specialists/specialists_provider_whole_sale_checkout.dart';
import '../../../ui/dashboard/healthcare_provider_dashboard/specialists/specialists_provider_wholesale_screen.dart';
import '../../../ui/dashboard/healthcare_provider_dashboard/specialists/specialists_providers_home_screen.dart';
import '../../../ui/dashboard/hmo/add_hospital_portal_screen.dart';
import '../../../ui/dashboard/hmo/create_claims_portal_screen.dart';
import '../../../ui/dashboard/hmo/create_hmo_plan.dart';
import '../../../ui/dashboard/hmo/create_settlements_portal_screen.dart';
import '../../../ui/dashboard/hmo/hmo_application_portal_screen.dart';
import '../../../ui/dashboard/hmo/hmo_claims_portal_screen.dart';
import '../../../ui/dashboard/hmo/hmo_dashboard.dart';
import '../../../ui/dashboard/hmo/hmo_home_screen.dart';
import '../../../ui/dashboard/hmo/hmo_hospital_network_portal_screen.dart';
import '../../../ui/dashboard/hmo/hmo_more_screen.dart';
import '../../../ui/dashboard/hmo/hmo_renewal_portal_screen.dart';
import '../../../ui/dashboard/hmo/hmo_settlement_portal_screen.dart';
import '../../../ui/dashboard/hmo/hmo_subscribers_portal_screen.dart';
import '../../../ui/dashboard/hmo/hmo_view_claims_portal_screen.dart';
import '../../../ui/dashboard/hmo/view_hmo_application_portal_screen.dart';
import '../../../ui/dashboard/hmo/view_hmo_renewal_portal_screen.dart';
import '../../../ui/dashboard/hmo/view_hmo_subscribers_portal_screen.dart';
import '../../../ui/dashboard/hmo/view_settlement_portal_screen.dart';
import '../../../ui/dashboard/home_screen.dart';
import '../../../ui/dashboard/profile/hmo/hmo_create_tiers_plan_management_screen.dart';
import '../../../ui/dashboard/profile/hmo/hmo_plan_tiers_management_screen.dart';
import '../../../ui/dashboard/profile/hmo/hmo_two_factor_auth_screen.dart';
import '../../../ui/dashboard/profile/hmo/hmo_two_factor_auth_verification_first_screen.dart';
import '../../../ui/dashboard/profile/hmo/hmo_two_factor_auth_verification_second_screen.dart';
import '../../../ui/dashboard/profile/notification_screen.dart';
import '../../../ui/dashboard/subscribers/application_form/application_form_screen.dart';
import '../../../ui/dashboard/subscribers/coorporate_form/coorporate_form_screen.dart';
import '../../../ui/dashboard/subscribers/family_form/family_form_screen.dart';
import '../../../ui/dashboard/subscribers/pro_health_sub_screen.dart';
import '../../../ui/dashboard/subscribers/subsribers_screen.dart';
import '../../../ui/dashboard/more_screen.dart';
import '../../../ui/dashboard/pharm_dashboard/pharm_dashboard.dart';
import '../../../ui/dashboard/pharm_dashboard/pharm_more_screen.dart';
import '../../../ui/dashboard/pharm_dashboard/reminder/pharm_view_medication_screen.dart';
import '../../../ui/dashboard/profile/faq_screen.dart';
import '../../../ui/dashboard/profile/health_care_profile/doctors_screen.dart';
import '../../../ui/dashboard/profile/health_care_profile/health_care_practitioner_profile_info_screen.dart';
import '../../../ui/dashboard/profile/health_care_profile/health_care_practitioner_profile_screen.dart';
import '../../../ui/dashboard/profile/health_care_profile/health_care_profile_info_screen.dart';
import '../../../ui/dashboard/profile/health_care_profile/health_care_profile_screen.dart';
import '../../../ui/dashboard/profile/health_care_profile/health_care_reset_pin_pad_screen.dart';
import '../../../ui/dashboard/profile/health_care_profile/health_care_setting_screen.dart';
import '../../../ui/dashboard/profile/health_care_profile/kyc/kyc_screen.dart';
import '../../../ui/dashboard/profile/health_care_profile/roles_and_permission_screen.dart';
import '../../../ui/dashboard/profile/hmo/hmo_profile_info_screen.dart';
import '../../../ui/dashboard/profile/hmo/hmo_profile_screen.dart';
import '../../../ui/dashboard/profile/hmo/hmo_reset_pin_pad_screen.dart';
import '../../../ui/dashboard/profile/hmo/hmo_setting_screen.dart';
import '../../../ui/dashboard/profile/hmo/kyc/hmo_kyc_screen.dart';
import '../../../ui/dashboard/profile/hmo/roles_and_permission_screen.dart';
import '../../../ui/dashboard/profile/hmo/users_screen.dart';
import '../../../ui/dashboard/profile/pharmacy_profile/kyc/kyc_screen.dart';
import '../../../ui/dashboard/profile/pharmacy_profile/pharmacy_profile_info_screen.dart';
import '../../../ui/dashboard/profile/pharmacy_profile/pharmacy_profile_screen.dart';
import '../../../ui/dashboard/profile/pharmacy_profile/pharmacy_reset_pin_pad_screen.dart';
import '../../../ui/dashboard/profile/pharmacy_profile/pharmacy_setting_screen.dart';
import '../../../ui/dashboard/profile/pharmacy_profile/roles_and_permission_screen.dart';
import '../../../ui/dashboard/profile/pharmacy_profile/users_screen.dart';
import '../../../ui/dashboard/profile/reset_pin_pad_screen.dart';
import '../../../ui/dashboard/profile/user_profile/profile_info_screen.dart';
import '../../../ui/dashboard/profile/user_profile/profile_screen.dart';
import '../../../ui/dashboard/profile/wallet/fund_screen.dart';
import '../../../ui/dashboard/profile/wallet/fund_wallet_pay_screen.dart';
import '../../../ui/dashboard/profile/wallet/transaction_screen.dart';
import '../../../ui/dashboard/profile/wallet/wallet_screen.dart';
import '../../../ui/dashboard/reminder/payment_status_screen.dart';
import '../../../ui/dashboard/reminder/view_medication_screen.dart';
import '../../../ui/dashboard/support/support_screen.dart';
import '../../../ui/onboarding/get_started_onboarding.dart';
import '../../../ui/onboarding/role_onboarding.dart';
import '../../../ui/onboarding/splash_screen.dart';
import '../../../ui/widget/accelerate_payment_view.dart';
import '../../../ui/widget/accelerate_payment_view_hmo_plan.dart';
import '../../../ui/widget/accelerate_payment_view_pharmacy.dart';
import '../../../ui/widget/accelerate_payment_view_wallet.dart';
import '../../../ui/widget/payment_success_submit_app_screen.dart';
import '../../api_folder/auth_api.dart';
import '../../api_folder/healthcare_api.dart';
import '../../api_folder/hmo_api.dart';
import '../../api_folder/pharm_auth_api.dart';
import '../../connect_end/contrast/contract_impl.dart';
import '../../connect_end/contrast/healthcare_contract_impl.dart';
import '../../connect_end/contrast/hmo_contract_impl.dart';
import '../../connect_end/contrast/pharm_contract_impl.dart';
import '../../connect_end/repo/healthcare_repo_impl.dart';
import '../../connect_end/repo/hmo_repo_impl.dart';
import '../../connect_end/repo/pharm_repo_impl.dart';
import '../../connect_end/repo/repo_impl.dart';
import '../../connect_end/view_model/auth_view_model.dart';
import '../../connect_end/view_model/health_care_view_model.dart';
import '../../connect_end/view_model/hmo_view_model.dart';
import '../../connect_end/view_model/pharm_auth_view_model.dart';
import '../manager/shared_preference.dart';
import '../network/network_service.dart';
import '../network/support_network_service.dart';

@StackedApp(
  routes: [
    MaterialRoute(page: Dashboard, initial: true),
    MaterialRoute(page: HomeScreen),
    MaterialRoute(page: PharmacyDashboard),
    MaterialRoute(page: RoleOnboarding),
    MaterialRoute(page: GetStartedOnboarding),
    MaterialRoute(page: SignUpScreen),
    MaterialRoute(page: ChangePhoneNumber),
    MaterialRoute(page: SetupPinScreen),
    MaterialRoute(page: LoginScreen),
    MaterialRoute(page: WelcomeScreen),
    MaterialRoute(page: ForgotPinScreen),
    MaterialRoute(page: ResetPinScreen),
    MaterialRoute(page: SuccessScreen),
    MaterialRoute(page: ProfileScreen),
    MaterialRoute(page: PharmacyProfileScreen),
    MaterialRoute(page: ProfileInfoScreen),
    MaterialRoute(page: PharmacyProfileInfoScreen),
    MaterialRoute(page: SupportScreen),
    MaterialRoute(page: ResetPinPadScreen),
    MaterialRoute(page: HealthCareResetPinPadScreen),
    MaterialRoute(page: PharmacyResetPinPadScreen),
    MaterialRoute(page: AskMeScreen),
    MaterialRoute(page: FaqScreen),
    MaterialRoute(page: SplashScreen),
    MaterialRoute(page: WalletScreen),
    MaterialRoute(page: TransactionScreen),
    MaterialRoute(page: FundScreen),
    MaterialRoute(page: FundWalletPayScreen),
    MaterialRoute(page: PaymentStatusScreen),
    MaterialRoute(page: ViewMedicationScreen),
    MaterialRoute(page: PharmViewMedicationScreen),
    MaterialRoute(page: PharmacySignUpScreen),
    MaterialRoute(page: PharmacySetupPinScreen),
    MaterialRoute(page: PharmacyLoginScreen),
    MaterialRoute(page: PharmacyChangePhoneNumber),
    MaterialRoute(page: PharmacyForgotPinScreen),
    MaterialRoute(page: PharmacyResetPinScreen),
    MaterialRoute(page: PharmacyWelcomeScreen),
    MaterialRoute(page: KycScreen),
    MaterialRoute(page: HMOKycScreen),
    MaterialRoute(page: HealthCareKycScreen),
    MaterialRoute(page: PharmacySettingScreen),
    MaterialRoute(page: PharmResetSuccessScreen),
    MaterialRoute(page: UsersScreen),
    MaterialRoute(page: DoctorScreen),
    MaterialRoute(page: RolesAndPermissionScreen),
    MaterialRoute(page: HealthCareRolesAndPermissionScreen),
    MaterialRoute(page: HealthCareHospitalAndClinicSignUpScreen),
    MaterialRoute(page: HealthCareDoctorSpecialistSignUpScreen),
    MaterialRoute(page: HealthCareLoginScreen),
    MaterialRoute(page: HealthCareChangePhoneNumber),
    MaterialRoute(page: HealthCareForgotPinScreen),
    MaterialRoute(page: HealthCareResetPinScreen),
    MaterialRoute(page: HealthCareResetSuccessScreen),
    MaterialRoute(page: HealthCareSetupPinScreen),
    MaterialRoute(page: HealthCareWelcomeScreen),
    MaterialRoute(page: BusinessProviderDashboard),
    MaterialRoute(page: BusinessProvidersHomeScreen),
    MaterialRoute(page: SpecialistsProviderDashboard),
    MaterialRoute(page: SpecialistsProvidersHomeScreen),
    MaterialRoute(page: HMODashboard),
    MaterialRoute(page: HMOHomeScreen),
    MaterialRoute(page: HealthCareProfileInfoScreen),
    MaterialRoute(page: HealthCareProfileScreen),
    MaterialRoute(page: HealthCareSettingScreen),
    MaterialRoute(page: AcceleratePaymentView),
    MaterialRoute(page: AcceleratePaymentViewPharmacy),
    MaterialRoute(page: AcceleratePaymentViewWallet),
    MaterialRoute(page: HealthCarePractitionerProfileInfoScreen),
    MaterialRoute(page: HealthCarePractitionerProfileScreen),
    MaterialRoute(page: HMOWelcomeScreen),
    MaterialRoute(page: HMOSignUpScreen),
    MaterialRoute(page: HMOSetupPinScreen),
    MaterialRoute(page: HMOResetSuccessScreen),
    MaterialRoute(page: HMOResetPinScreen),
    MaterialRoute(page: HMOLoginScreen),
    MaterialRoute(page: HMOForgotPinScreen),
    MaterialRoute(page: HMOChangePhoneNumber),
    MaterialRoute(page: HMOProfileInfoScreen),
    MaterialRoute(page: HMOProfileScreen),
    MaterialRoute(page: HMOResetPinPadScreen),
    MaterialRoute(page: HMOSettingScreen),
    MaterialRoute(page: HMORolesAndPermissionScreen),
    MaterialRoute(page: HMOUsersScreen),
    MaterialRoute(page: ProHealthSubScreen),
    MaterialRoute(page: ApplicationFormScreen),
    MaterialRoute(page: SubsribersScreen),
    MaterialRoute(page: FamilyFormScreen),
    MaterialRoute(page: CoorporateFormScreen),
    MaterialRoute(page: AcceleratePaymentViewHmoPlan),
    MaterialRoute(page: PaymentSuccessSubmitAppScreen),
    MaterialRoute(page: CreateHmoPlan),
    MaterialRoute(page: HmoApplicationPortalScreen),
    MaterialRoute(page: ViewHmoApplicationPortalScreen),
    MaterialRoute(page: HmoSubscribersPortalScreen),
    MaterialRoute(page: ViewHmoSubscribersPortalScreen),
    MaterialRoute(page: HmoHospitalNetworkPortalScreen),
    MaterialRoute(page: HmoAddHospitalNetworkPortalScreen),
    MaterialRoute(page: HmoRenewalPortalScreen),
    MaterialRoute(page: ViewHmoRenewalPortalScreen),
    MaterialRoute(page: HmoClaimsPortalScreen),
    MaterialRoute(page: CreateClaimsPortalScreen),
    MaterialRoute(page: ViewHmoClaimsPortalScreen),
    MaterialRoute(page: CreateSettlementsPortalScreen),
    MaterialRoute(page: ViewHmoSettlementsPortalScreen),
    MaterialRoute(page: HmoSettlementPortalScreen),
    MaterialRoute(page: HMOTwoFactorAuthScreen),
    MaterialRoute(page: HmoTwoFactorAuthVerificationSecondScreen),
    MaterialRoute(page: HmoTwoFactorAuthVerificationFirstScreen),
    MaterialRoute(page: HmoPlanTiersManagementScreen),
    MaterialRoute(page: HmoCreateTiersPlanManagementScreen),
    MaterialRoute(page: HealthcareViewMedicationScreen),
    MaterialRoute(page: BusinessProviderAddToCartScreen),
    MaterialRoute(page: BusinessProviderWholeSaleCheckout),
    MaterialRoute(page: BusinessProviderOrderScreen),
    MaterialRoute(page: SpecialistsProviderWholesale),
    MaterialRoute(page: SpecialistsProviderWholeSaleCheckout),
    MaterialRoute(page: SpecialistsProviderOrderScreen),
    MaterialRoute(page: SpecialistsProviderAddToCartScreen),
    CustomRoute(
      page: NotificationScreen,
      transitionsBuilder: TransitionsBuilders.slideLeft,
      durationInMilliseconds: 300,
    ),
    CustomRoute(
      page: MoreScreen,
      transitionsBuilder: TransitionsBuilders.slideRight,
      durationInMilliseconds: 300,
    ),
    CustomRoute(
      page: PharmMoreScreen,
      transitionsBuilder: TransitionsBuilders.slideRight,
      durationInMilliseconds: 300,
    ),
    CustomRoute(
      page: BusinessProvidersMoreScreen,
      transitionsBuilder: TransitionsBuilders.slideRight,
      durationInMilliseconds: 300,
    ),
    CustomRoute(
      page: SpecialistsProvidersMoreScreen,
      transitionsBuilder: TransitionsBuilders.slideRight,
      durationInMilliseconds: 300,
    ),
    CustomRoute(
      page: HMOMoreScreen,
      transitionsBuilder: TransitionsBuilders.slideRight,
      durationInMilliseconds: 300,
    ),
  ],
  dependencies: [
    LazySingleton(classType: NavigationService),
    LazySingleton(classType: DialogService),
    LazySingleton(classType: SnackbarService),
    LazySingleton(classType: SharedPreferencesService),
    LazySingleton(classType: NetworkService),
    LazySingleton(classType: SupportNetworkService),
    LazySingleton(classType: AuthApi),
    LazySingleton(classType: PharmApi),
    LazySingleton(classType: HealthcareApi),
    LazySingleton(classType: HMOApi),
    LazySingleton(classType: AuthContractsImpl),
    LazySingleton(classType: PharmContractsImpl),
    LazySingleton(classType: HealthcareContractsImpl),
    LazySingleton(classType: HMOContractsImpl),
    LazySingleton(classType: AuthRepoImpl),
    LazySingleton(classType: PharmRepoImpl),
    LazySingleton(classType: HealthcareRepoImpl),
    LazySingleton(classType: HMORepoImpl),
    LazySingleton(classType: AuthViewModel),
    Factory(classType: PharmViewModel),
    Factory(classType: HealthCareViewModel),
    Factory(classType: HMOViewModel),
  ],
  logger: StackedLogger(),
)
class App {}
