import 'package:stacked/stacked.dart';
import 'package:stacked/stacked_annotations.dart';
import 'package:stacked_services/stacked_services.dart';
import '../../../ui/authentication/health_care/health_care_doctor_specialist_signup_screen.dart';
import '../../../ui/authentication/health_care/health_care_hospital_and_clinic_signup_screen.dart';
import '../../../ui/authentication/pharmacy/pharm_change_no_screen.dart';
import '../../../ui/authentication/pharmacy/pharm_forgot_pin_screen.dart';
import '../../../ui/authentication/pharmacy/pharm_login_screen.dart';
import '../../../ui/authentication/pharmacy/pharm_reset_pin_screen.dart';
import '../../../ui/authentication/pharmacy/pharm_reset_success_screen.dart';
import '../../../ui/authentication/pharmacy/pharm_setup_pin_screen.dart';
import '../../../ui/authentication/pharmacy/pharm_sign_up_screen.dart';
import '../../../ui/authentication/pharmacy/welcome_screen.dart';
import '../../../ui/authentication/user/change_phone_number.dart';
import '../../../ui/authentication/user/forgot_pin_screen.dart';
import '../../../ui/authentication/user/login_screen.dart';
import '../../../ui/authentication/user/reset_pin_screen.dart';
import '../../../ui/authentication/user/setup_pin_screen.dart';
import '../../../ui/authentication/user/sign_up_screen.dart';
import '../../../ui/authentication/user/success_screen.dart';
import '../../../ui/authentication/user/welcome_screen.dart';
import '../../../ui/dashboard/ask_me_screen.dart';
import '../../../ui/dashboard/dashboard_screen.dart';
import '../../../ui/dashboard/more_screen.dart';
import '../../../ui/dashboard/notification/empty_notification.dart';
import '../../../ui/dashboard/pharm_dashboard/pharm_dashboard.dart';
import '../../../ui/dashboard/pharm_dashboard/pharm_more_screen.dart';
import '../../../ui/dashboard/pharm_dashboard/reminder/pharm_view_medication_screen.dart';
import '../../../ui/dashboard/profile/faq_screen.dart';
import '../../../ui/dashboard/profile/pharmacy_profile/kyc/kyc_screen.dart';
import '../../../ui/dashboard/profile/pharmacy_profile/pharmacy_profile_info_screen.dart';
import '../../../ui/dashboard/profile/pharmacy_profile/pharmacy_profile_screen.dart';
import '../../../ui/dashboard/profile/pharmacy_profile/pharmacy_setting_screen.dart';
import '../../../ui/dashboard/profile/pharmacy_profile/roles_and_permission_screen.dart';
import '../../../ui/dashboard/profile/pharmacy_profile/users_screen.dart';
import '../../../ui/dashboard/profile/reset_pin_pad_screen.dart';
import '../../../ui/dashboard/profile/user_profile/profile_info_screen.dart';
import '../../../ui/dashboard/profile/user_profile/profile_screen.dart';
import '../../../ui/dashboard/profile/wallet/fund_screen.dart';
import '../../../ui/dashboard/profile/wallet/fund_wallet_pay_screen.dart';
import '../../../ui/dashboard/profile/wallet/transaction_screen.dart';
import '../../../ui/dashboard/profile/wallet/wallet_screen.dart';
import '../../../ui/dashboard/reminder/payment_status_screen.dart';
import '../../../ui/dashboard/reminder/view_medication_screen.dart';
import '../../../ui/dashboard/support/support_screen.dart';
import '../../../ui/onboarding/get_started_onboarding.dart';
import '../../../ui/onboarding/role_onboarding.dart';
import '../../../ui/onboarding/splash_screen.dart';
import '../../../ui/widget/accelerate_payment_view.dart';
import '../../api_folder/auth_api.dart';
import '../../api_folder/pharm_auth_api.dart';
import '../../connect_end/contrast/contract_impl.dart';
import '../../connect_end/contrast/pharm_contract_impl.dart';
import '../../connect_end/repo/pharm_repo_impl.dart';
import '../../connect_end/repo/repo_impl.dart';
import '../../connect_end/view_model/auth_view_model.dart';
import '../../connect_end/view_model/pharm_auth_view_model.dart';
import '../manager/shared_preference.dart';
import '../network/network_service.dart';
import '../network/support_network_service.dart';

@StackedApp(
  routes: [
    MaterialRoute(page: Dashboard, initial: true),
    MaterialRoute(page: PharmacyDashboard),
    MaterialRoute(page: RoleOnboarding),
    MaterialRoute(page: GetStartedOnboarding),
    MaterialRoute(page: SignUpScreen),
    MaterialRoute(page: ChangePhoneNumber),
    MaterialRoute(page: SetupPinScreen),
    MaterialRoute(page: LoginScreen),
    MaterialRoute(page: WelcomeScreen),
    MaterialRoute(page: ForgotPinScreen),
    MaterialRoute(page: ResetPinScreen),
    MaterialRoute(page: SuccessScreen),
    MaterialRoute(page: ProfileScreen),
    MaterialRoute(page: PharmacyProfileScreen),
    MaterialRoute(page: ProfileInfoScreen),
    MaterialRoute(page: PharmacyProfileInfoScreen),
    MaterialRoute(page: SupportScreen),
    MaterialRoute(page: ResetPinPadScreen),
    MaterialRoute(page: AskMeScreen),
    MaterialRoute(page: EmptyNotification),
    MaterialRoute(page: FaqScreen),
    MaterialRoute(page: SplashScreen),
    MaterialRoute(page: WalletScreen),
    MaterialRoute(page: TransactionScreen),
    MaterialRoute(page: FundScreen),
    MaterialRoute(page: FundWalletPayScreen),
    MaterialRoute(page: PaymentStatusScreen),
    MaterialRoute(page: ViewMedicationScreen),
    MaterialRoute(page: PharmViewMedicationScreen),
    MaterialRoute(page: PharmacySignUpScreen),
    MaterialRoute(page: PharmacySetupPinScreen),
    MaterialRoute(page: PharmacyLoginScreen),
    MaterialRoute(page: PharmacyChangePhoneNumber),
    MaterialRoute(page: PharmacyForgotPinScreen),
    MaterialRoute(page: PharmacyResetPinScreen),
    MaterialRoute(page: PharmacyWelcomeScreen),
    MaterialRoute(page: KycScreen),
    MaterialRoute(page: PharmacySettingScreen),
    MaterialRoute(page: PharmResetSuccessScreen),
    MaterialRoute(page: UsersScreen),
    MaterialRoute(page: RolesAndPermissionScreen),
    MaterialRoute(page: HealthCareHospitalAndClinicSignUpScreen),
    MaterialRoute(page: HealthCareDoctorSpecialistSignUpScreen),
    // MaterialRoute(page: AcceleratePaymentView),
    CustomRoute(
      page: MoreScreen,
      transitionsBuilder: TransitionsBuilders.slideRight,
      durationInMilliseconds: 300,
    ),
    CustomRoute(
      page: PharmMoreScreen,
      transitionsBuilder: TransitionsBuilders.slideRight,
      durationInMilliseconds: 300,
    ),
  ],
  dependencies: [
    LazySingleton(classType: NavigationService),
    LazySingleton(classType: DialogService),
    LazySingleton(classType: SnackbarService),
    LazySingleton(classType: SharedPreferencesService),
    LazySingleton(classType: NetworkService),
    LazySingleton(classType: SupportNetworkService),
    LazySingleton(classType: AuthApi),
    LazySingleton(classType: PharmApi),
    LazySingleton(classType: AuthContractsImpl),
    LazySingleton(classType: PharmContractsImpl),
    LazySingleton(classType: AuthRepoImpl),
    LazySingleton(classType: PharmRepoImpl),
    LazySingleton(classType: AuthViewModel),
    Factory(classType: PharmViewModel),
  ],
  logger: StackedLogger(),
)
class App {}
